# Generated by Django 6.0.5 on 2026-05-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icecream',
            options={'verbose_name': 'Мороженое', 'verbose_name_plural': 'Мороженые'},
        ),
        migrations.RenameField(
            model_name='icecream',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AddField(
            model_name='icecream',
            name='flavor_type',
            field=models.CharField(choices=[('gelato', 'Джелато'), ('icecream', 'Мороженое'), ('sorbet', 'Сорбет')], default='icecream', max_length=20, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='icecream',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='icecream',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярное'),
        ),
        migrations.AddField(
            model_name='icecream',
            name='is_seasonal',
            field=models.BooleanField(default=False, verbose_name='Сезонное'),
        ),
        migrations.AddField(
            model_name='icecream',
            name='is_vegan',
            field=models.BooleanField(default=False, verbose_name='Веганское'),
        ),
        migrations.AddField(
            model_name='icecream',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень'), ('winter', 'Зима')], max_length=20, null=True, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='photo',
            field=models.ImageField(upload_to='ice_creams/', verbose_name='Фото'),
        ),
    ]
